# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"urlrequest": "01_helper.ipynb",
         "updatescore": "01_helper.ipynb"}

modules = ["core.py",
           "helper.py"]

doc_url = "https://StevedeP.github.io/ClickUpShift/"

git_url = "https://github.com/StevedeP/ClickUpShift/"

def custom_doc_links(name): return None
